# Generated by Django 5.1.7 on 2025-08-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sample_images/')),
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('base_colour', models.CharField(blank=True, max_length=50)),
                ('feature_vector', models.BinaryField()),
            ],
        ),
    ]
